name: Obfuscate code and push to heroku branch

on:
  push:
    branches:
      - main
jobs:
  obfuscate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js (14)
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code from main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main_code

      - name: Obfuscate Javascript
        run: |
          npx javascript-obfuscator ./ --output ./ --options-preset high-obfuscation --dead-code-injection false

      - name: Push to remote master branch
        working-directory: main_code
        run: |
          COMMIT_NAME=$(git log -1 --format=%s) 
          git config --global user.email "73202350+slow@users.noreply.github.com"
          git config --global user.name "eternal"
          git stash
          git fetch origin
          git checkout heroku
          git merge --squash --allow-unrelated-histories -Xtheirs stash
          git add -A
          git commit -m "${COMMIT_NAME}"
          git push
